package com.sanchezjp.modelo.entities;
// Generated 27-dic-2017 22:08:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {

     private Integer id;
     private String codArticulo;
     private String descripcion;
     private double precio;
     private int stock;
     private int iva;
     private Integer descuento;
     private String obsoleto;
     private Set detallesFacturas = new HashSet(0);

    public Articulos() {
    }

	
    public Articulos(String descripcion, double precio, int stock, int iva, String obsoleto) {
        this.descripcion = descripcion;
        this.precio = precio;
        this.stock = stock;
        this.iva = iva;
        this.obsoleto = obsoleto;
    }
    public Articulos(String codArticulo, String descripcion, double precio, int stock, int iva, Integer descuento, String obsoleto, Set detallesFacturas) {
       this.codArticulo = codArticulo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.stock = stock;
       this.iva = iva;
       this.descuento = descuento;
       this.obsoleto = obsoleto;
       this.detallesFacturas = detallesFacturas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodArticulo() {
        return this.codArticulo;
    }
    
    public void setCodArticulo(String codArticulo) {
        this.codArticulo = codArticulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public int getIva() {
        return this.iva;
    }
    
    public void setIva(int iva) {
        this.iva = iva;
    }
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }
    public String getObsoleto() {
        return this.obsoleto;
    }
    
    public void setObsoleto(String obsoleto) {
        this.obsoleto = obsoleto;
    }
    public Set getDetallesFacturas() {
        return this.detallesFacturas;
    }
    
    public void setDetallesFacturas(Set detallesFacturas) {
        this.detallesFacturas = detallesFacturas;
    }

    /**
     * Establece la entidad como activa o inactiva (Borrado Lógico)
     * @param activo indica si está obsoleto (false) o no (true)
     */
    public void setActivo(Boolean activo){
        if(activo){
            setObsoleto(OBSOLETO.NO.toString());
        }else{
            setObsoleto(OBSOLETO.YES.toString());
        }
    }
    
    /**
     * Indica si se ha practicado un borrado lógico sobre el elemento
     * @return TRUE si no hay borrado lógico (no obsoleto), FALSE en caso contrario.
     */
    public Boolean isActivo(){
        return obsoleto.equals(OBSOLETO.NO.toString());
    }


}


