package com.sanchezjp.modelo.entities;
// Generated 27-dic-2017 22:08:04 by Hibernate Tools 4.3.1



/**
 * DetallesFactura generated by hbm2java
 */
public class DetallesFactura  implements java.io.Serializable {


     private DetallesFacturaId id;
     private Articulos articulos;
     private Facturas facturas;
     private int unidades;
     private double precio;
     private Integer descuento;
     private int iva;
     private String obsoleto;

    public DetallesFactura() {
    }

	
    public DetallesFactura(DetallesFacturaId id, Articulos articulos, Facturas facturas, int unidades, double precio, int iva, String obsoleto) {
        this.id = id;
        this.articulos = articulos;
        this.facturas = facturas;
        this.unidades = unidades;
        this.precio = precio;
        this.iva = iva;
        this.obsoleto = obsoleto;
    }
    public DetallesFactura(DetallesFacturaId id, Articulos articulos, Facturas facturas, int unidades, double precio, Integer descuento, int iva, String obsoleto) {
       this.id = id;
       this.articulos = articulos;
       this.facturas = facturas;
       this.unidades = unidades;
       this.precio = precio;
       this.descuento = descuento;
       this.iva = iva;
       this.obsoleto = obsoleto;
    }
   
    public DetallesFacturaId getId() {
        return this.id;
    }
    
    public void setId(DetallesFacturaId id) {
        this.id = id;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public int getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(int unidades) {
        this.unidades = unidades;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }
    public int getIva() {
        return this.iva;
    }
    
    public void setIva(int iva) {
        this.iva = iva;
    }
    public String getObsoleto() {
        return this.obsoleto;
    }
    
    public void setObsoleto(String obsoleto) {
        this.obsoleto = obsoleto;
    }




}


