package com.sanchezjp.modelo.entities;
// Generated 27-dic-2017 22:08:04 by Hibernate Tools 4.3.1



/**
 * DetallesFacturaId generated by hbm2java
 */
public class DetallesFacturaId  implements java.io.Serializable {


     private int numDetalle;
     private int factura;

    public DetallesFacturaId() {
    }

    public DetallesFacturaId(int numDetalle, int factura) {
       this.numDetalle = numDetalle;
       this.factura = factura;
    }
   
    public int getNumDetalle() {
        return this.numDetalle;
    }
    
    public void setNumDetalle(int numDetalle) {
        this.numDetalle = numDetalle;
    }
    public int getFactura() {
        return this.factura;
    }
    
    public void setFactura(int factura) {
        this.factura = factura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallesFacturaId) ) return false;
		 DetallesFacturaId castOther = ( DetallesFacturaId ) other; 
         
		 return (this.getNumDetalle()==castOther.getNumDetalle())
 && (this.getFactura()==castOther.getFactura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumDetalle();
         result = 37 * result + this.getFactura();
         return result;
   }   


}


